networks:
  carbon_network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_carbon
    networks:
      - carbon_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_carbon
    networks:
      - carbon_network
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_carbon:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_carbon:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"

  mongodb:
    image: mongo:6.0
    container_name: mongodb_carbon
    networks:
      - carbon_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.0
    container_name: mlflow_carbon
    networks:
      - carbon_network
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0

  pyspark:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: pyspark_carbon
    networks:
      - carbon_network
    user: root
    volumes:
      - ../processing:/app/processing
      - ../myfile.env:/app/myfile.env
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    command: start.sh jupyter lab --NotebookApp.token=''

volumes:
  mongo_data: