version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_carbon
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_carbon
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:6.0
    container_name: mongodb_carbon
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.0
    container_name: mlflow_carbon
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0

volumes:
  mongo_data: