FROM apache/airflow:2.7.0

USER airflow

RUN pip install --no-cache-dir \
    kafka-python==3.0.10 \
    pymysql==1.1.2 \
    pymongo==4.10.1 \
    requests==2.31.0 \
    python-dotenv==1.0.0 \
    pandas==2.0.3 \
    numpy==1.24.4 \
    scipy==1.10.1 \
    scikit-learn==1.3.2 \
    xgboost==2.1.4 \
    mlflow==2.9.0 \
    shap==0.44.1